### ISSUE TITLE
make -C external throw  error

### ISSUE THREAD

**Issue by QuyTran** [aryx/pfff#1]
Hi @aryx, I see some errors when trying to execute the command

> ➜  pfff git:(master) make -C external
> set -e; for i in battery_included/empty battery_included/json-wheel  battery_included/ocamlgraph battery_included/ocamlgtk battery_included/ocamlcairo; do /Library/Developer/CommandLineTools/usr/bin/make -C $i all || exit 1; done
> ocamlc -c empty.ml
> ocamlc -a -o netstring.cma empty.cmo
> ocamlc -a -o netsys.cma empty.cmo
> ocamlc -a -o netsys_oothr.cma empty.cmo
> rm empty.cmo
> ocamlc -g -dtypes      -thread -c json_type.ml
> File "json_type.ml", line 1:
> Error: Could not find the .cmi file for interface json_type.mli.
> make[1]: *** [json_type.cmo] Error 2
> make: *** [all] Error 1

**Comment by aryx** [comment]
can you try make -C external depend first?
(I'll update the configure script if it works)

**Comment by QuyTran** [comment]
cooool, you save my life.
