### ISSUE TITLE
missing features for codegraph

### ISSUE THREAD

**Issue by QuyTran** [aryx/pfff#2]
hi @aryx, it seems codegraph miss a lot features from the main repo

> ➜  Working ./pfff/codegraph
> Usage: codegraph [options] <dir>
> Doc: https://github.com/facebook/pfff/wiki/Codegraph
> Options:
>   -deps                <in|out|inout>
>   -dots_threshold      <int> when do we introduce '...' entries
>   -gen_bottomup_layer  <graph_file> <output>
>   -test_load_db        <file>
>   -test_big_grep       <file>
>   -test_layer          <file>
>   -test_refactoring    <file>
>   -debugger            option to set if launched inside ocamldebug
>   -profile             output profiling information
>   -verbose
>   -version             guess what
>   -help                Display this list of options
>   --help               Display this list of options
> ➜  Working ./pfff/codegraph -version
> CodeGraph version: 0.34

> root@5f6faa44aec8:/workdir# codegraph -version
> CodeGraph version: 0.29
> root@5f6faa44aec8:/workdir# codegraph -help
> Usage: codegraph [options] <dir>
> Doc: https://github.com/facebook/pfff/wiki/Codegraph
> Options:
>   -deps  <in|out|inout>
>   -dots_threshold  <int> when do we introduce '...' entries
>   -lang  <str> choose language (default = ml) (for -build)
>   -o  <dir> save graph_code.marshall in another dir (for -build)
>   -derived_data  generate also TAGS, layers, light db, etc (for -build)
>   -class_analysis  resolve some method calls
>   -symlinks  follow symlinks (for -build)
>   -no_fake_node  no fake nodes when use-def mismatches (for -build)
> 
>   -gen_bottomup_layer  <graph_file> <output>
>   -build  <dirs> build a graph_code.marshall database
>   -build_stdlib  <src> <dst>
>   -adjust_graph  <graph> <adjust_file> <whitelist> <dstfile>
> 
>   -test_backward_deps  <graph>
>   -test_protected_to_private  <graph>
>   -test_thrift_alive  <graph>
>   -test_pad  <graph>
>   -test_layering  <graph>
>   -test_xta  <graph>
>   -test_dotfile_of_deps  <dir>
>   -test_dotfile_of_dotdepend  <file>
>   -test_load_db  <file>
>   -test_big_grep  <file>
>   -test_layer  <file>
>   -test_refactoring  <file>
>   -debugger  option to set if launched inside ocamldebug
>   -profile  output profiling information
>   -verbose
>   -version  guess what
>   -help  Display this list of options
>   --help  Display this list of options

Could you please add them also? thanks!!

**Comment by aryx** [comment]
The functionality of codegraph has been split in 2 programs.
There is codegraph for the UI and codegraph_build for the command-line program building the graph database.
use codegraph_build first and then codegraph on what codegraph_build built

**Comment by QuyTran** [comment]
oh, nice, can build the marshall file now. But I can't see the graph

> ➜  Working ./pfff/codegraph seafas
> 
> (process:12853): Gtk-WARNING **: 12:03:11.162: Locale not supported by C library.
> 	Using the fallback 'C' locale.
> 2018-06-12 12:03:11.196 codegraph[12853:706580] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
> Fatal error: exception File "common2.ml", line 6018, characters 2-8: Assertion failed

**Comment by aryx** [comment]
can you do in a shell:
$ export OCAMLRUNPARAM=b
$ ./pfff/codegraph /absolute_path/to/seafas

and show me the full backtrace if there is one.

**Comment by QuyTran** [comment]
> ➜  Working export OCAMLRUNPARAM=b
> ➜  Working
> ➜  Working
> ➜  Working ./pfff/codegraph seafas
> 
> (process:13130): Gtk-WARNING **: 13:51:54.620: Locale not supported by C library.
> 	Using the fallback 'C' locale.
> 2018-06-12 13:51:54.659 codegraph[13130:779277] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
> Fatal error: exception File "common2.ml", line 6018, characters 2-8: Assertion failed
> Raised at file "common2.ml", line 6018, characters 2-26
> Called from file "main_codegraph.ml", line 303, characters 14-47
> Called from file "common.ml", line 1271, characters 12-16
> Re-raised at file "common.ml", line 1269, characters 8-302
> Called from file "common.ml", line 1239, characters 45-49
> Called from file "common.ml", line 87, characters 14-18
> Re-raised at file "common.ml", line 92, characters 10-11
> Called from file "common.ml", line 1236, characters 6-10
> Called from file "main_codegraph.ml", line 455, characters 2-54

**Comment by wu-s-john** [comment]
Got the same issue that @QuyTran  received. Is this being fixed?

**Comment by aryx** [comment]
Ok, rebuild the graph and rerun codegraph and it should now work:
$ codegraph_build -lang php /path/to/project
$ codegraph /path/to/project

**Comment by wu-s-john** [comment]
I have a web project that I would like to visualize, but it doesn't seem to be working.

I tried running

$ ./codegraph_build -lang web /path/to/project

Then, I got the following error:

`Fatal error: exception Failure("Find_source: unsupported language: web")
`

I tried using "javascript" as well. It doesn't seem to work

**Comment by QuyTran** [comment]
can see the GUI right now, thanks @aryx
