### ISSUE TITLE
Question: Is pfff being adopted by r2c?

### ISSUE THREAD

**Issue by ClaudiuCeia** [aryx/pfff#8]
Hi Yoann,

I've used pfff at Facebook some years ago and I'm glad to see it's still being worked on. I'd like to start using it again but just wanted to check if the r2c fork is going to become the officially maintained fork. 

Thanks!

**Comment by aryx** [comment]
Yes, I now work at r2c so this will be the officially maintained fork.
I've split the repositories in multiple one though, so the pfff repos contains mostly all the parsers, but sgrep, scheck, codemap, codegraph (the programs using the parsers) are now outside, some under r2c, some under aryx.

**Comment by ClaudiuCeia** [comment]
Gotcha, thanks for the info, awesome that you're still maintaining this! 

All the best!
